# Documentation: https://rmk.rs/docs/configuration.html
# 参考https://github.com/HaoboGu/rmk/blob/main/examples/use_config/nrf52840_ble/keyboard.toml

[keyboard]
name = "makey42"
product_name = "makey42"
vendor_id = 0xFEED
product_id = 0x6060
manufacturer = "mark1028"
chip = "nrf52840"
usb_enable = true

[matrix]
# Row and col pins are mandatory
# matrix_type = "normal"    # matrix_type = "direct_pin"
row_pins = ["P0_17", "P1_09", "P0_30", "P0_31", "P0_29"]
col_pins = ["P0_07", "P0_12", "P0_04", "P0_08", "P0_06", "P0_26", "P0_15", "P0_02", "P1_02", "P1_13"]
# row2col = false
# RMK uses col2row as the default matrix diode direction, if you want to use a row2col matrix, add `row2col = true`
# row2col = true

[layout]
rows = 5
cols = 10
layers = 2
matrix_map = """
(0,0) (0,1) (0,2) (0,3) (0,4) (0,5) (0,6)
(1,0) (1,1) (1,2) (1,3) (1,4) (1,5) (1,6)
(2,0) (2,1) (2,2) (2,3) (2,4) (2,5) (2,6)
(3,0) (3,1) (3,2) (3,3) (3,4) (3,5) (3,6) (3,7)
(4,0) (4,1) (4,2) (4,3) (4,4) (4,5) (4,6) (4,7) (4,8) (4,9)
"""

# layer 0 (default):
# (the number comes from the order of '[[layer]] entries' in the file)
[[layer]]
name = "base_layer" #optional name for the layer
keys = """
Escape Grave    Kc1  Kc2  Kc3  Kc4   Kc5  
F1     Tab      Q    W    E    R     T            
F2     CapsLock A    S    D    F     G       
F3     LShift   Z    X    C    V     B     N     
F4     LCtrl    LGui LAlt RAlt RCtrl Space Enter Delete Backspace
"""
# Encoder 0 - CW: AudioVolUp, CCW: AudioVolDown
# encoders = [["AudioVolUp", "AudioVolDown"]["AudioVolUp", "AudioVolDown"]["AudioVolUp", "AudioVolDown"]]  ？

# layer 1:
[[layer]]
name = "mouse_navigation" #optional name for the layer
keys = """
Escape Grave    Kc1  Kc2  Kc3  Kc4   Kc5  
F1     Tab      Q    W    E    R     T            
F2     CapsLock A    S    D    F     G       
F3     LShift   Z    X    C    V     B     N     
F4     LCtrl    LGui LAlt RAlt RCtrl Space Enter Delete Backspace
"""
# Encoder 0 - CW: AudioVolUp, CCW: AudioVolDown
# encoders = [["AudioVolUp", "AudioVolDown"]["AudioVolUp", "AudioVolDown"]["AudioVolUp", "AudioVolDown"]]  ？


[ble]
enabled = true
battery_adc_pin = "P0_05"
# charge_state.pin = "P0_07"
# charge_state.low_active = true
adc_divider_measured = 2000
adc_divider_total = 2820

[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
capslock.pin = "P0_20"   # capslock = { pin = "PIN_0", low_active = true }
capslock.low_active = false
# charge_led.pin = "P1_00"
# charge_led.low_active = false

# Encoder 0
[[input_device.encoder]]
pin_a = "P0_13"
pin_b = "P0_24"
#phase = "default" 
phase = "resolution" # 分辨率选项，此项为自定义分辨率
resolution = 4      # 自定义分辨率
reverse = true       # 旋转方向：反向
internal_pullup = true  # 使用mcu内部上拉电阻

# Encoder 1
[[input_device.encoder]]
pin_a = "P1_11"
pin_b = "P1_10"
#phase = "default" 
phase = "resolution" 
resolution = 4
reverse = true
internal_pullup = true  # 使用mcu内部上拉电阻

# Encoder 2
[[input_device.encoder]]
pin_a = "P0_03"
pin_b = "P0_28"
#phase = "default" 
phase = "resolution"
resolution = 4
reverse = true 
# Whether to use the MCU's internal pull-up resistor, default to false 是否使用MCU的内部上拉电阻，默认为false
internal_pullup = true  # 使用mcu内部上拉电阻，如果编码器没有外接上拉电阻，则必须开启此项功能！
